services:
  postgres:
    image: postgres:16
    container_name: postgres_webflux
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webflux_db
      POSTGRES_USER: webflux
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
